# Generated by Django 4.1 on 2022-08-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myapps',
            options={'verbose_name': 'car', 'verbose_name_plural': 'cars'},
        ),
    ]
