# Generated by Django 4.1 on 2022-08-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myapp',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='myapp',
            name='age',
            field=models.IntegerField(default=None, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='myapp',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
